/// 强类型响应接口
/// Typed Response Interface
///
/// 用于桥接预编译的强类型响应模型（如 Retrofit 生成的 `BaseResult<T>`）。
/// Used to bridge pre-compiled typed response models (e.g., `BaseResult<T>` generated by Retrofit).
/// 项目端的 BaseResult 只需实现此接口，即可无缝接入 `KoiTypedRequestExecutor`。
/// The project's BaseResult only needs to implement this interface to seamlessly integrate with `KoiTypedRequestExecutor`.
///
/// ## 使用示例 / Usage Example
///
/// ```dart
/// // 项目端已有的 BaseResult，只需加上 implements
/// // The project's existing BaseResult, simply add implements
/// @JsonSerializable(genericArgumentFactories: true)
/// class BaseResult<T> implements KoiTypedResponse<T> {
///   BaseResult(this.code, this.message, this.data);
///
///   @override
///   final int? code;
///
///   @override
///   final String? message;
///
///   @override
///   final T? data;
///
///   @override
///   bool get isSuccess => code == 200 || code == 0;
/// }
/// ```
abstract class KoiTypedResponse<T> {
  /// 请求是否业务成功
  /// Whether the request is a business success
  bool get isSuccess;

  /// 业务错误码（可选）
  /// Business error code (optional)
  int? get code;

  /// 业务错误消息（可选）
  /// Business error message (optional)
  String? get message;

  /// 实际业务数据
  /// Actual business data
  T? get data;
}
