import 'package:koi_network/src/adapters/network_adapters.dart';
import 'package:koi_network/src/executors/request_executor.dart';
import 'package:koi_network/src/koi_network_constants.dart'
    show KoiNetworkConstants;
import 'package:koi_network/src/models/request_execution_options.dart';
import 'package:koi_network/src/models/typed_response.dart';

/// 强类型批量请求选项。
/// Options for typed batch request execution.
///
/// 配置强类型批量请求的执行行为。
/// Controls how typed batch requests are executed.
class TypedBatchRequestOptions {
  /// 创建强类型批量请求选项。
  /// Creates typed batch request options.
  ///
  /// - [concurrent] 是否并发执行所有请求 / Whether to execute all requests concurrently
  /// - [showLoading] 是否显示加载提示 / Whether to show loading prompt
  /// - [loadingText] 加载提示文本 / Loading prompt text
  /// - [stopOnFirstError] 是否在第一个失败时停止 / Whether to stop on the first error
  const TypedBatchRequestOptions({
    this.concurrent = true,
    this.showLoading = true,
    this.loadingText,
    this.stopOnFirstError = false,
  });

  /// 是否并发执行。
  /// Whether requests should run concurrently.
  final bool concurrent;

  /// 是否显示加载提示。
  /// Whether to show a loading prompt.
  final bool showLoading;

  /// 加载提示文本。
  /// Text shown in the loading prompt.
  final String? loadingText;

  /// 是否在第一个失败时停止。
  /// Whether to stop on the first failure.
  final bool stopOnFirstError;
}

/// Koi 强类型请求执行器。
/// Executor for strongly typed requests in Koi Network.
///
/// 用于执行已由 Retrofit、OpenAPI 等工具预解析的强类型请求。
/// Executes typed requests that have already been pre-parsed by tools such as Retrofit or OpenAPI.
///
/// 请求函数返回实现了 [KoiTypedResponse] 的对象（如 `BaseResult<T>`），
/// The request function returns an object implementing [KoiTypedResponse]
/// (for example `BaseResult<T>`),
/// 而不是原始的 Dio `Response`。
/// rather than a raw Dio `Response`.
///
/// 本执行器复用了 [KoiNetworkAdapters] 的 Loading、Error、Logger 调度体系，
/// This executor reuses the Loading, Error, and Logger coordination system from
/// [KoiNetworkAdapters],
/// 让动态解析与强类型预编译场景保持一致的用户体验。
/// so both dynamic parsing and strongly typed flows share a consistent experience.
///
/// ## 使用方式 / Usage
///
/// ```dart
/// // 方式一：直接使用 Retrofit 生成的 API 调用
/// // Method 1: Directly use the API call generated by Retrofit
/// final user = await KoiTypedRequestExecutor.execute<User>(
///   request: () => userApi.getUser(1), // 返回 / Returns BaseResult<User>
/// );
///
/// // 方式二：静默请求（不显示加载和错误提示）
/// // Method 2: Silent request (does not show loading or error prompts)
/// final data = await KoiTypedRequestExecutor.executeSilent<MyData>(
///   request: () => api.getData(),
/// );
/// ```
class KoiTypedRequestExecutor {
  /// 执行单个强类型请求。
  /// Executes a single typed request.
  ///
  /// [request] 返回 [KoiTypedResponse] 的异步函数 / Async function returning a [KoiTypedResponse]
  /// [options] 请求执行选项 / Request execution options
  static Future<T?> execute<T>({
    required Future<KoiTypedResponse<T>> Function() request,
    RequestExecutionOptions<T>? options,
  }) async {
    final opts = options ?? RequestExecutionOptions<T>();

    try {
      // 显示加载提示
      // Show loading prompt
      if (opts.showLoading) {
        KoiNetworkAdapters.loading.showLoading(message: opts.loadingText);
      }

      // 执行请求（已经过 Retrofit 反序列化）
      // Execute request (already deserialized by Retrofit)
      final result = await request();

      // 隐藏加载提示
      // Hide loading prompt
      if (opts.showLoading) {
        KoiNetworkAdapters.loading.hideLoading();
      }

      // 自定义成功检查
      // Custom success check
      if (opts.successCheck != null) {
        if (!opts.successCheck!(result.data)) {
          throw RequestLogicException<T>(
            'Operation failed',
            data: result.data,
            errorCode: result.code,
          );
        }
      }

      // 自定义数据检查
      // Custom data check
      if (opts.dataCheck != null) {
        if (!opts.dataCheck!(result.data)) {
          throw RequestLogicException<T>(
            'Invalid data format',
            data: result.data,
            errorCode: result.code,
          );
        }
        opts.onSuccess?.call(result.data);
        return result.data;
      }

      // 处理结果
      // Process result
      if (result.isSuccess) {
        if (opts.dataNotNull && result.data == null) {
          throw RequestLogicException<T>(
            'No data available',
            data: result.data,
            errorCode: result.code,
          );
        }

        opts.onSuccess?.call(result.data);
        return result.data;
      } else {
        // 业务逻辑错误
        // Business logic error
        throw RequestLogicException<T>(
          result.message ?? 'Operation failed',
          data: result.data,
          errorCode: result.code,
        );
      }
    } catch (e) {
      KoiNetworkAdapters.logger.error(e.toString());

      // 隐藏加载提示
      // Hide loading prompt
      if (opts.showLoading) {
        KoiNetworkAdapters.loading.hideLoading();
      }

      // 错误处理
      // Error handling
      final errorMessage = KoiRequestExecutor.getErrorMessage(e);

      if (opts.showError) {
        KoiNetworkAdapters.errorHandler.showError(errorMessage);
      }

      opts.onError?.call(e, errorMessage);

      if (opts.needRethrow) {
        rethrow;
      }

      return null;
    } finally {
      opts.onFinally?.call();
    }
  }

  /// 执行静默强类型请求，不显示加载和错误提示。
  /// Executes a silent typed request without loading or error feedback.
  static Future<T?> executeSilent<T>({
    required Future<KoiTypedResponse<T>> Function() request,
    void Function(T? data)? onSuccess,
    void Function(Object e, String message)? onError,
    void Function()? onFinally,
    bool dataNotNull = true,
    bool Function(T? data)? successCheck,
    bool Function(T? data)? dataCheck,
  }) async {
    return execute<T>(
      request: request,
      options: RequestExecutionOptions<T>(
        showLoading: false,
        showError: false,
        onSuccess: onSuccess,
        onError: onError,
        onFinally: onFinally,
        dataNotNull: dataNotNull,
      ),
    );
  }

  /// 执行快速强类型请求，不显示加载但会显示错误。
  /// Executes a quick typed request that hides loading but still shows errors.
  static Future<T?> executeQuick<T>({
    required Future<KoiTypedResponse<T>> Function() request,
    void Function(T? data)? onSuccess,
    void Function(Object e, String message)? onError,
    void Function()? onFinally,
    bool dataNotNull = true,
    bool Function(T? data)? successCheck,
    bool Function(T? data)? dataCheck,
  }) async {
    return execute<T>(
      request: request,
      options: RequestExecutionOptions<T>(
        showLoading: false,
        onSuccess: onSuccess,
        onError: onError,
        onFinally: onFinally,
        dataNotNull: dataNotNull,
        successCheck: successCheck,
        dataCheck: dataCheck,
      ),
    );
  }

  /// 执行强类型批量请求。
  /// Executes a batch of typed requests.
  static Future<List<T?>> executeBatch<T>(
    List<Future<KoiTypedResponse<T>> Function()> requests, {
    TypedBatchRequestOptions? options,
  }) async {
    final opts = options ?? const TypedBatchRequestOptions();

    try {
      // 显示加载提示
      // Show loading prompt
      if (opts.showLoading) {
        KoiNetworkAdapters.loading.showLoading(
          message: opts.loadingText ?? 'Loading...',
        );
      }

      List<T?> results;

      if (opts.concurrent) {
        // 并发执行
        // Concurrent execution
        final futures = requests.map(
          (request) => _executeSingleInBatch<T>(
            request,
            stopOnError: opts.stopOnFirstError,
          ),
        );
        results = await Future.wait(futures);
      } else {
        // 顺序执行
        // Sequential execution
        results = [];
        for (final request in requests) {
          try {
            final result = await _executeSingleInBatch<T>(
              request,
              stopOnError: opts.stopOnFirstError,
            );
            results.add(result);
          } catch (e) {
            if (opts.stopOnFirstError) {
              rethrow;
            }
            results.add(null); // coverage:ignore-line
          }
        }
      }

      // 隐藏加载提示
      // Hide loading prompt
      if (opts.showLoading) {
        KoiNetworkAdapters.loading.hideLoading();
      }

      return results;
    } catch (e) {
      // 隐藏加载提示
      // Hide loading prompt
      if (opts.showLoading) {
        KoiNetworkAdapters.loading.hideLoading();
      }

      if (KoiNetworkConstants.debugEnabled) {
        KoiNetworkAdapters.logger.error('❌ Typed batch request failed', e);
      }

      rethrow;
    }
  }

  /// 执行批量中的单个强类型请求。
  /// Executes a single typed request inside a batch.
  static Future<T?> _executeSingleInBatch<T>(
    Future<KoiTypedResponse<T>> Function() request, {
    bool stopOnError = false,
  }) async {
    try {
      final result = await request();

      if (result.isSuccess) {
        return result.data;
      } else {
        if (stopOnError) {
          throw RequestLogicException<T>(
            result.message ?? 'Request failed',
            data: result.data,
            errorCode: result.code,
          );
        }
        return null;
      }
    } catch (e) {
      if (stopOnError) {
        rethrow;
      }

      if (KoiNetworkConstants.debugEnabled) {
        KoiNetworkAdapters.logger.warning(
          '⚠️ Single typed request in batch failed',
          e,
        );
      }

      return null;
    }
  }

  /// 执行带重试的强类型请求。
  /// Executes a typed request with retry support.
  ///
  /// ⚠️ 注意：Dio 已通过 dio_smart_retry 拦截器自动处理网络层重试。
  /// ⚠️ Note: Dio already handles network-layer retries automatically via the dio_smart_retry interceptor.
  ///
  /// 此方法主要用于应用层业务逻辑重试，例如业务错误码重试。
  /// This method is mainly intended for application-layer retries, such as retrying on business error codes.
  static Future<T?> executeWithRetry<T>({
    required Future<KoiTypedResponse<T>> Function() request,
    int maxRetries = 3,
    Duration delay = const Duration(seconds: 1),
    RequestExecutionOptions<T>? options,
  }) async {
    final opts = options ?? RequestExecutionOptions<T>();

    if (KoiNetworkConstants.debugEnabled) {
      KoiNetworkAdapters.logger.info(
        '🔄 [TypedRetry] App-level retry enabled (max $maxRetries)',
      );
    }

    for (var attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        return await execute<T>(
          request: request,
          options: opts.copyWith(
            showLoading: attempt == 0 && opts.showLoading,
            showError: attempt == maxRetries && opts.showError,
            needRethrow: true,
          ),
        );
      } catch (e) {
        if (attempt == maxRetries) {
          if (KoiNetworkConstants.debugEnabled) {
            KoiNetworkAdapters.logger.warning(
              '❌ [TypedRetry] Failed after $maxRetries retries',
            );
          }
          rethrow;
        }

        if (KoiNetworkConstants.debugEnabled) {
          KoiNetworkAdapters.logger.debug(
            '🔄 [TypedRetry] Attempt ${attempt + 1}/$maxRetries',
            e,
          );
        }

        if (delay.inMilliseconds > 0) {
          await Future<void>.delayed(delay);
        }
      }
    }

    return null;
  }
}
